site_name: blind
site_description: test
repo_url: https://github.com/hyerim1048/django-restframework-for-blind
site_dir: site
copyright: Copyright &copy; 2019, <a href="https://github.com/hyerim1048">hyerim1048</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
